name: Kit
version: 1.0
main: me.happyorks.Kit.Main
description: simple kit plugin
depend: [Vault]

commands:
    kit:
        usage: /<command>
        aliases: [getkit]
        description: get kit
    ci: 
        usage: /<command>
        aliases: [clearinventory, clearinv]
        description: clears inventory